### ISSUE TITLE
Add an example my-event.md file in the README

### ISSUE THREAD

**Issue by bzg** [hjonin/eleventy-plugin-calendar#1]
On top of the `calendar.njk` and `calendar-event.njk` examples, a simple content/blog.my-event.md example could help avoid simple mistakes for newbies (like me) such as forgetting the "s" in `tags`, or the "s" in `tags: events`, etc.

WDYT?

**Comment by hjonin** [comment]
I have added a link to a sample event, and the schema of the event variables you can use in an event frontmatter in the [documentation](https://github.com/codegouvfr/eleventy-plugin-calendar#usage). Would it be sufficient?

**Comment by bzg** [comment]
Yes, it is, thank you!
